// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	FlywaySchemaHistory string
	Products            string
	TechnicalStacks     string
	Users               string
}{
	FlywaySchemaHistory: "flyway_schema_history",
	Products:            "products",
	TechnicalStacks:     "technical_stacks",
	Users:               "users",
}
