// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("FlywaySchemaHistories", testFlywaySchemaHistories)
	t.Run("Products", testProducts)
	t.Run("TechnicalStacks", testTechnicalStacks)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("FlywaySchemaHistories", testFlywaySchemaHistoriesDelete)
	t.Run("Products", testProductsDelete)
	t.Run("TechnicalStacks", testTechnicalStacksDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("FlywaySchemaHistories", testFlywaySchemaHistoriesQueryDeleteAll)
	t.Run("Products", testProductsQueryDeleteAll)
	t.Run("TechnicalStacks", testTechnicalStacksQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("FlywaySchemaHistories", testFlywaySchemaHistoriesSliceDeleteAll)
	t.Run("Products", testProductsSliceDeleteAll)
	t.Run("TechnicalStacks", testTechnicalStacksSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("FlywaySchemaHistories", testFlywaySchemaHistoriesExists)
	t.Run("Products", testProductsExists)
	t.Run("TechnicalStacks", testTechnicalStacksExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("FlywaySchemaHistories", testFlywaySchemaHistoriesFind)
	t.Run("Products", testProductsFind)
	t.Run("TechnicalStacks", testTechnicalStacksFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("FlywaySchemaHistories", testFlywaySchemaHistoriesBind)
	t.Run("Products", testProductsBind)
	t.Run("TechnicalStacks", testTechnicalStacksBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("FlywaySchemaHistories", testFlywaySchemaHistoriesOne)
	t.Run("Products", testProductsOne)
	t.Run("TechnicalStacks", testTechnicalStacksOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("FlywaySchemaHistories", testFlywaySchemaHistoriesAll)
	t.Run("Products", testProductsAll)
	t.Run("TechnicalStacks", testTechnicalStacksAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("FlywaySchemaHistories", testFlywaySchemaHistoriesCount)
	t.Run("Products", testProductsCount)
	t.Run("TechnicalStacks", testTechnicalStacksCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("FlywaySchemaHistories", testFlywaySchemaHistoriesHooks)
	t.Run("Products", testProductsHooks)
	t.Run("TechnicalStacks", testTechnicalStacksHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("FlywaySchemaHistories", testFlywaySchemaHistoriesInsert)
	t.Run("FlywaySchemaHistories", testFlywaySchemaHistoriesInsertWhitelist)
	t.Run("Products", testProductsInsert)
	t.Run("Products", testProductsInsertWhitelist)
	t.Run("TechnicalStacks", testTechnicalStacksInsert)
	t.Run("TechnicalStacks", testTechnicalStacksInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("ProductToUserUsingUser", testProductToOneUserUsingUser)
	t.Run("TechnicalStackToProductUsingProduct", testTechnicalStackToOneProductUsingProduct)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("ProductToTechnicalStacks", testProductToManyTechnicalStacks)
	t.Run("UserToProducts", testUserToManyProducts)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("ProductToUserUsingProducts", testProductToOneSetOpUserUsingUser)
	t.Run("TechnicalStackToProductUsingTechnicalStacks", testTechnicalStackToOneSetOpProductUsingProduct)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("ProductToTechnicalStacks", testProductToManyAddOpTechnicalStacks)
	t.Run("UserToProducts", testUserToManyAddOpProducts)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("FlywaySchemaHistories", testFlywaySchemaHistoriesReload)
	t.Run("Products", testProductsReload)
	t.Run("TechnicalStacks", testTechnicalStacksReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("FlywaySchemaHistories", testFlywaySchemaHistoriesReloadAll)
	t.Run("Products", testProductsReloadAll)
	t.Run("TechnicalStacks", testTechnicalStacksReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("FlywaySchemaHistories", testFlywaySchemaHistoriesSelect)
	t.Run("Products", testProductsSelect)
	t.Run("TechnicalStacks", testTechnicalStacksSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("FlywaySchemaHistories", testFlywaySchemaHistoriesUpdate)
	t.Run("Products", testProductsUpdate)
	t.Run("TechnicalStacks", testTechnicalStacksUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("FlywaySchemaHistories", testFlywaySchemaHistoriesSliceUpdateAll)
	t.Run("Products", testProductsSliceUpdateAll)
	t.Run("TechnicalStacks", testTechnicalStacksSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
