// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("FlywaySchemaHistories", testFlywaySchemaHistoriesUpsert)

	t.Run("Products", testProductsUpsert)

	t.Run("TechnicalStacks", testTechnicalStacksUpsert)

	t.Run("Users", testUsersUpsert)
}
