name: portfolioGo
# host: portfolio-database.c0wy7zi5zmc7.ap-northeast-1.rds.amazonaws.com
host: postgresql
port: 5432
# password: Higashi624
password: pass
user: local_user
schema: portfolioGo
sslmode: disable
maxidleconns: 5
maxopenconns: 5
connmaxlifetime: 8h # string (use for time.ParseDuration())
databasedriver: postgres
