name: portfolioGo
host: portfolio-database.c0wy7zi5zmc7.ap-northeast-1.rds.amazonaws.com
port: 5432
password: Higashi624
user: local_user
schema: portfolioGo
sslmode: disable
maxidleconns: 5
maxopenconns: 5
connmaxlifetime: 8h # string (use for time.ParseDuration())
databasedriver: postgres
